[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
ibverbs = { path = "../ibverbs", features = ["serde"] }
bincode = { version = "2.0.1", features = ["serde"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
