[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
ibverbs = { path = "../ibverbs" }
rand = "0.9.2"
rand_chacha = "0.9.0"
serde_json = "1.0.143"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
