[package]
name = "zerocopy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
serde_json = "1.0.141"
ibverbs = { path = "../ibverbs" }
crc32fast = "1.5.0"
tokio = { version = "1.47.1", features = ["full"] }
futures = "0.3.31"
